export const apiRoutes = {
  '/users': '/users',
  '/posts': '/posts',
  '/comments': '/comments',
} as const
export type ApiRouteType = keyof typeof apiRoutes

export enum pathsEnum {
  login = '/auth/login',
  register = '/auth/register',
  dashboardAnalytics = '/dashboard/analytics',
  dashboardBusinessHealth = '/dashboard/business-health',
  dashboardBusinessHealthV2 = '/dashboard/business-health-v2',
  automation = '/automation',
  transactions = '/transactions',
  projects = '/projects',
  accounts = '/accounts',
  beneficiaries = '/beneficiaries',
  beneficiary = '/beneficiaries/:id',
  cashFlowActivities = '/reports/cash-flow/by-activities',
  cashFlowCategories = '/reports/cash-flow/by-categories',
  cashFlowBeneficiaries = '/reports/cash-flow/by-beneficiaries',
  cashFlowAccounts = '/reports/cash-flow/by-accounts',
  cashFlowProjects = '/reports/cash-flow/by-projects',
  cashFlowProjectsCategory = '/reports/cash-flow/by-projects-categories',
  myLegalEntities = '/references/my-legal-entities',
  categories = '/references/categories',
  users = '/references/users',
  rolesAndPermissions = '/references/roles-permissions',
  addresses = '/references/addresses',
  historyOfBankStatements = '/history-of-bank-statements',
  paymentCalendar = '/payment-calendar',
  profitLossReport = '/reports/profit-loss',
  balanceReport = '/reports/balance',
  profile = '/profile',
  integrations = '/integrations',
  currencies = '/currencies',
  company = '/company',
  uploadPlanedBudget = '/reports/upload-planed-budget',
  verification = '/verification',
  welcome = '/welcome',
  subscriptions = '/subscriptions',
  employees = '/employees',
  employeesReport = '/employees-report',
  sessions = '/sessions',
}

export const titlePathnameMap = {
  [pathsEnum.automation]: 'Automation',
  [pathsEnum.transactions]: 'Transactions',
  [pathsEnum.projects]: 'Projects',
  [pathsEnum.accounts]: 'Accounts',
  [pathsEnum.beneficiaries]: 'Beneficiaries',
  [pathsEnum.cashFlowActivities]: 'cashFlow',
  [pathsEnum.cashFlowCategories]: 'cashFlow',
  [pathsEnum.cashFlowBeneficiaries]: 'cashFlow',
  [pathsEnum.cashFlowAccounts]: 'cashFlow',
  [pathsEnum.myLegalEntities]: 'legalEntities',
  [pathsEnum.categories]: 'Categories',
  [pathsEnum.users]: 'Users',
  [pathsEnum.addresses]: 'Addresses',
  [pathsEnum.historyOfBankStatements]: 'historyOfBankStatements',
  [pathsEnum.beneficiary]: 'Beneficiary',
  [pathsEnum.balanceReport]: 'balanceReport',
  [pathsEnum.profitLossReport]: 'profitLossReport',
  [pathsEnum.profile]: 'Profile',
  [pathsEnum.integrations]: 'Integrations',
  [pathsEnum.paymentCalendar]: 'paymentCalendar',
  [pathsEnum.currencies]: 'Currencies',
  [pathsEnum.company]: 'myCompany',
  [pathsEnum.rolesAndPermissions]: 'rolesAndPermissions',
  [pathsEnum.dashboardAnalytics]: 'Analytics',
  [pathsEnum.dashboardBusinessHealth]: 'businessHealth',
  [pathsEnum.dashboardBusinessHealthV2]: 'businessHealth',
  [pathsEnum.verification]: 'Verification',
  [pathsEnum.welcome]: 'startOfWork',
  [pathsEnum.subscriptions]: 'Subscriptions',
  [pathsEnum.cashFlowProjects]: 'cashFlow',
  [pathsEnum.cashFlowProjectsCategory]: 'cashFlow',
  [pathsEnum.employees]: 'Employees',
  [pathsEnum.employeesReport]: 'employeesReport',
  [pathsEnum.sessions]: 'Sessions',
} as const
